name: Create and Add Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Zip File
      run: zip -r my_archive.zip .

    - name: Add Zip File to Staging Area
      run: git add my_archive.zip

    - name: Commit Changes
      run: git commit -m "Add my_archive.zip"

    - name: Add Zip File to Repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT2 }}
        branch: main
        directory: .

    - name: Cleanup
      run: rm my_archive.zip
