name: Create Archive
on: [push]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "Flozz2"
        git config --global user.email "fzarbo2007@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git*'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
      with:
        github_token: ${{ secrets.PAT2 }}
        branch: main